### ISSUE TITLE
Change the color of the logo

### ISSUE THREAD

**Issue by Ojha-CL** [Charu053/github-crash-course#1]
I think it looks better if the main title is bit more blue.

The styling rule could be changed like this:

```css
h1 {
  color: #0ecda0;
}

a {
  color: #ac89fe;
}

```
